### ISSUE TITLE
Text formatter affects team names, scoreboard objective names and advancement names in chat, even when deactivated.

### ISSUE THREAD

**Issue by ghost** [Zoutelande/Custom-Text-Tablist#3]
All of the above listed refuse to show up in chat, console or command responses, and sometimes even clears the rest of the chat line.

**Comment by kearfy** [comment]
In addition to @MorganHofmann the stop-command doesn't work either (most of the time, it did sometimes).

**Comment by smonnnn** [comment]
Thanks for opening this issue, I'll try and fix it asap!

**Comment by kearfy** [comment]
Thanks!

**Comment by smonnnn** [comment]
Is the issue present in the 1.15.2 branch or the 1.16 version? The 1.16 version has not been updated past the snapshots so might not work right.

**Comment by ghost** [comment]
We run the 1.15.2 branch!

**Comment by smonnnn** [comment]
I have fixed the deactivation bug and for now made it so advancements don't go through the text formatter at all. I will soon update the mod #with more configurability per translation key, so that it's possible to enable/disable formatting per message type.

**Comment by smonnnn** [comment]
Should be fixed completely in v1.3.0, if any issues still occur please let me know.
