### ISSUE TITLE
Config does not save properly, causing text to fail to save/load

### ISSUE THREAD

**Issue by Infinidoge** [Zoutelande/Custom-Text-Tablist#4]
It appears that instead of saving the config to a file, it instead tries to create a folder named `color.json`, which fails to load a saved config since, as one might expect, it is difficult to save text as a folder.
When attempting to manually correct for this by making a color.json file manually for it to save to, the server crashes on start.
Relevant logs: https://pastebin.com/wLtNUYyw

**Comment by skythebro** [comment]
I've had this problem too, found any workaround for this? Or a fix?

**Comment by Infinidoge** [comment]
If I had a setup for modding with Fabric I would attempt to fix myself and make a pull request, but as of right now my current modding projectis a 1.8.9 client-side mod for playing on Hypixel.
